name: app-a—Åtions
on: 
  - push
  - pull_request

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} 
      - name: npm install
        run: make install
        env:
          CI: true
      - name: Run linter
        run: make lint